language: cpp

compiler: gcc

jdk:
  - oraclejdk7

before_install:
  - sudo apt-get update

install:
  - sudo apt-get install python-dev python-numpy

before_script:
  - mkdir build
  - cd build
  - cmake ..

script: make -j4
